apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pureftpd.fullname" . }}-users
  labels:
    {{- include "pureftpd.labels" . | nindent 4 }}
data:
  users.conf: |
    {{- range .Values.users }}
    {{ .username }}:{{ .uid }}
    {{- end }}
