apiVersion: v1
kind: Service
metadata:
  name: {{ include "vsftpd.fullname" . }}
  labels:
    {{- include "vsftpd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "vsftpd.selectorLabels" . | nindent 4 }}
  ports:
    - name: ftp
      port: {{ .Values.service.ports.ftp }}
      targetPort: ftp
      protocol: TCP
    {{- $min := .Values.service.ports.passive.min }}
    {{- $max := .Values.service.ports.passive.max }}
    {{- range untilStep (int $min) (add1 (int $max) | int) 1 }}
    - name: pasv-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
