apiVersion: v1
kind: Service
metadata:
  name: {{ include "pureftpd.fullname" . }}
  labels:
    {{- include "pureftpd.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "pureftpd.selectorLabels" . | nindent 4 }}
  ports:
    - name: ftp
      port: 21
      targetPort: 21
      nodePort: {{ .Values.service.ports.ftp }}
      protocol: TCP
    {{- $min := .Values.service.ports.passive.min }}
    {{- $max := .Values.service.ports.passive.max }}
    {{- range untilStep (int $min) (add1 (int $max) | int) 1 }}
    - name: pasv-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      nodePort: {{ . }}
      protocol: TCP
    {{- end }}
