services:
  pure-ftpd:
    image: pure-ftpd:local
    ports:
      - "21:21"
      - "32100-32110:32100-32110"
    volumes:
      - ./users.conf:/etc/pure-ftpd/users.conf:ro
      - ./passwords:/etc/pure-ftpd/passwords:ro
      - etc-data:/etc-data
      # - ./data:/home

volumes:
  etc-data:
